name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir la imagen Docker
      - name: Build Docker image
        run: docker build -t usuario_docker_hub/nombre_imagen:latest .

      # Subir la imagen a Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push usuario_docker_hub/nombre_imagen:latest
